# Generated by Django 4.2.6 on 2023-10-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_account_number', models.CharField(max_length=10)),
                ('from_account_number', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typee', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
